import { AD, AE, AF, AG, AI, AL, AM, AO, AR, AS, AT, AU, AW, AZ, 
    BA, BB, BD, BE, BF, BG, BH, BI, BJ, BL, BM, BN, BO, BQ, 
    BR, BS, BT, BW, BY, BZ, CA, CC, CD, CF, CG, CH, CI, CK, 
    CL, CM, CN, CO, CR, CU, CV, CW, CX, CY, CZ, DE, DJ, DK, 
    DM, DO, DZ, EC, EE, EG, EH, ER, ES, ET, FI, FJ, FM, FO, 
    FR, GA, GB, GD, GE, GF, GG, GH, GI, GL, GM, GN, GP, GQ, 
    GR, GT, GU, GW, GY, HK, HN, HR, HT, HU, ID, IE, IL, IM, 
    IN, IO, IQ, IR, IS, IT, JE, JM, JO, JP, KE, KG, KH, KI, 
    KM, KN, KP, KR, KW, KY, KZ, LA, LB, LC, LI, LK, LR, LS, 
    LT, LU, LV, LY, MA, MC, MD, ME, MF, MG, MH, MK, ML, MM, 
    MN, MO, MP, MQ, MR, MS, MT, MU, MV, MW, MX, MY, MZ, NA, 
    NC, NE, NF, NG, NI, NL, NO, NP, NR, NU, NZ, OM, PA, PE, 
    PF, PG, PH, PK, PL, PM, PN, PR, PS, PT, PW, PY, QA, RE, 
    RO, RS, RU, RW, SA, SB, SC, SD, SE, SG, SH, SI, SJ, SK, 
    SL, SM, SN, SO, SR, SS, ST, SV, SX, SY, SZ, TC, TD, TG, 
    TH, TJ, TK, TL, TM, TN, TO, TR, TT, TV, TW, TZ, UA, UG, US, 
    UY, UZ, VA, VC, VE, VG, VI, VN, VU, WF, WS, YE, YT, ZA, 
    ZM, ZW } from 'country-flag-icons/react/3x2'

const flag = [
    {Component: AD, title: 'Andorra', code: '+376'},
    {Component: AE, title: 'United Arab Emirates', code: '+971'},
    {Component: AF, title: 'Afghanistan', code: '+93'},
    {Component: AG, title: 'Antigua and Barbuda', code: '+1-268'},
    {Component: AI, title: 'Anguilla', code: '+1-264'},
    {Component: AL, title: 'Albania', code: '+355'},
    {Component: AM, title: 'Armenia', code: '+374'},
    {Component: AO, title: 'Angola', code: '+244'},
    {Component: AR, title: 'Argentina', code: '+54'},
    {Component: AS, title: 'American Samoa', code: '+1-684'},
    {Component: AT, title: 'Austria', code: '+43'},
    {Component: AU, title: 'Australia', code: '+61'},
    {Component: AW, title: 'Aruba', code: '+297'},
    {Component: AZ, title: 'Azerbaijan', code: '+994'},
    {Component: BA, title: 'Bosnia and Herzegovina', code: '+387'},
    {Component: BB, title: 'Barbados', code: '+1-246'},
    {Component: BD, title: 'Bangladesh', code: '+880'},
    {Component: BE, title: 'Belgium', code: '+32'},
    {Component: BF, title: 'Burkina Faso', code: '+226'},
    {Component: BG, title: 'Bulgaria', code: '+359'},
    {Component: BH, title: 'Bahrain', code: '+973'},
    {Component: BI, title: 'Burundi', code: '+257'},
    {Component: BJ, title: 'Benin', code: '+229'},
    {Component: BL, title: 'Saint Barthélemy', code: '+590'},
    {Component: BM, title: 'Bermuda', code: '+1-441'},
    {Component: BN, title: 'Brunei', code: '+673'},
    {Component: BO, title: 'Bolivia', code: '+591'},
    {Component: BQ, title: 'Caribbean Netherlands', code: '+599'},
    {Component: BR, title: 'Brazil', code: '+55'},
    {Component: BS, title: 'Bahamas', code: '+1-242'},
    {Component: BT, title: 'Bhutan', code: '+975'},
    {Component: BW, title: 'Botswana', code: '+267'},
    {Component: BY, title: 'Belarus', code: '+375'},
    {Component: BZ, title: 'Belize', code: '+501'},
    {Component: CA, title: 'Canada', code: '+1'},
    {Component: CC, title: 'Cocos (Keeling) Islands', code: '+61'},
    {Component: CD, title: 'Democratic Republic of the Congo', code: '+243'},
    {Component: CF, title: 'Central African Republic', code: '+236'},
    {Component: CG, title: 'Republic of the Congo', code: '+242'},
    {Component: CH, title: 'Switzerland', code: '+41'},
    {Component: CI, title: 'Côte d’Ivoire', code: '+225'},
    {Component: CK, title: 'Cook Islands', code: '+682'},
    {Component: CL, title: 'Chile', code: '+56'},
    {Component: CM, title: 'Cameroon', code: '+237'},
    {Component: CN, title: 'China', code: '+86'},
    {Component: CO, title: 'Colombia', code: '+57'},
    {Component: CR, title: 'Costa Rica', code: '+506'},
    {Component: CU, title: 'Cuba', code: '+53'},
    {Component: CV, title: 'Cape Verde', code: '+238'},
    {Component: CW, title: 'Curaçao', code: '+599'},
    {Component: CX, title: 'Christmas Island', code: '+61'},
    {Component: CY, title: 'Cyprus', code: '+357'},
    {Component: CZ, title: 'Czech Republic', code: '+420'},
    {Component: DE, title: 'Germany', code: '+49'},
    {Component: DJ, title: 'Djibouti', code: '+253'},
    {Component: DK, title: 'Denmark', code: '+45'},
    {Component: DM, title: 'Dominica', code: '+1-767'},
    {Component: DO, title: 'Dominican Republic', code: '+1-809'},
    {Component: DZ, title: 'Algeria', code: '+213'},
    {Component: EC, title: 'Ecuador', code: '+593'},
    {Component: EE, title: 'Estonia', code: '+372'},
    {Component: EG, title: 'Egypt', code: '+20'},
    {Component: EH, title: 'Western Sahara', code: '+212'},
    {Component: ER, title: 'Eritrea', code: '+291'},
    {Component: ES, title: 'Spain', code: '+34'},
    {Component: ET, title: 'Ethiopia', code: '+251'},
    {Component: FI, title: 'Finland', code: '+358'},
    {Component: FJ, title: 'Fiji', code: '+679'},
    {Component: FM, title: 'Micronesia', code: '+691'},
    {Component: FO, title: 'Faroe Islands', code: '+298'},
    {Component: FR, title: 'France', code: '+33'},
    {Component: GA, title: 'Gabon', code: '+241'},
    {Component: GB, title: 'United Kingdom', code: '+44'},
    {Component: GD, title: 'Grenada', code: '+1-473'},
    {Component: GE, title: 'Georgia', code: '+995'},
    {Component: GF, title: 'French Guiana', code: '+594'},
    {Component: GG, title: 'Guernsey', code: '+44'},
    {Component: GH, title: 'Ghana', code: '+233'},
    {Component: GI, title: 'Gibraltar', code: '+350'},
    {Component: GL, title: 'Greenland', code: '+299'},
    {Component: GM, title: 'Gambia', code: '+220'},
    {Component: GN, title: 'Guinea', code: '+224'},
    {Component: GP, title: 'Guadeloupe', code: '+590'},
    {Component: GQ, title: 'Equatorial Guinea', code: '+240'},
    {Component: GR, title: 'Greece', code: '+30'},
    {Component: GT, title: 'Guatemala', code: '+502'},
    {Component: GU, title: 'Guam', code: '+1-671'},
    {Component: GW, title: 'Guinea-Bissau', code: '+245'},
    {Component: GY, title: 'Guyana', code: '+592'},
    {Component: HK, title: 'Hong Kong', code: '+852'},
    {Component: HN, title: 'Honduras', code: '+504'},
    {Component: HR, title: 'Croatia', code: '+385'},
    {Component: HT, title: 'Haiti', code: '+509'},
    {Component: HU, title: 'Hungary', code: '+36'},
    {Component: ID, title: 'Indonesia', code: '+62'},
    {Component: IE, title: 'Ireland', code: '+353'},
    {Component: IL, title: 'Israel', code: '+972'},
    {Component: IM, title: 'Isle of Man', code: '+44'},
    {Component: IN, title: 'India', code: '+91'},
    {Component: IO, title: 'British Indian Ocean Territory', code: '+246'},
    {Component: IQ, title: 'Iraq', code: '+964'},
    {Component: IR, title: 'Iran', code: '+98'},
    {Component: IS, title: 'Iceland', code: '+354'},
    {Component: IT, title: 'Italy', code: '+39'},
    {Component: JE, title: 'Jersey', code: '+44'},
    {Component: JM, title: 'Jamaica', code: '+1-876'},
    {Component: JO, title: 'Jordan', code: '+962'},
    {Component: JP, title: 'Japan', code: '+81'},
    {Component: KE, title: 'Kenya', code: '+254'},
    {Component: KG, title: 'Kyrgyzstan', code: '+996'},
    {Component: KH, title: 'Cambodia', code: '+855'},
    {Component: KI, title: 'Kiribati', code: '+686'},
    {Component: KM, title: 'Comoros', code: '+269'},
    {Component: KN, title: 'Saint Kitts and Nevis', code: '+1-869'},
    {Component: KP, title: 'North Korea', code: '+850'},
    {Component: KR, title: 'South Korea', code: '+82'},
    {Component: KW, title: 'Kuwait', code: '+965'},
    {Component: KY, title: 'Cayman Islands', code: '+1-345'},
    {Component: KZ, title: 'Kazakhstan', code: '+7'},
    {Component: LA, title: 'Laos', code: '+856'},
    {Component: LB, title: 'Lebanon', code: '+961'},
    {Component: LC, title: 'Saint Lucia', code: '+1-758'},
    {Component: LI, title: 'Liechtenstein', code: '+423'},
    {Component: LK, title: 'Sri Lanka', code: '+94'},
    {Component: LR, title: 'Liberia', code: '+231'},
    {Component: LS, title: 'Lesotho', code: '+266'},
    {Component: LT, title: 'Lithuania', code: '+370'},
    {Component: LU, title: 'Luxembourg', code: '+352'},
    {Component: LV, title: 'Latvia', code: '+371'},
    {Component: LY, title: 'Libya', code: '+218'},
    {Component: MA, title: 'Morocco', code: '+212'},
    {Component: MC, title: 'Monaco', code: '+377'},
    {Component: MD, title: 'Moldova', code: '+373'},
    {Component: ME, title: 'Montenegro', code: '+382'},
    {Component: MF, title: 'Saint Martin', code: '+590'},
    {Component: MG, title: 'Madagascar', code: '+261'},
    {Component: MH, title: 'Marshall Islands', code: '+692'},
    {Component: MK, title: 'North Macedonia', code: '+389'},
    {Component: ML, title: 'Mali', code: '+223'},
    {Component: MM, title: 'Myanmar', code: '+95'},
    {Component: MN, title: 'Mongolia', code: '+976'},
    {Component: MO, title: 'Macau', code: '+853'},
    {Component: MP, title: 'Northern Mariana Islands', code: '+1-670'},
    {Component: MQ, title: 'Martinique', code: '+596'},
    {Component: MR, title: 'Mauritania', code: '+222'},
    {Component: MS, title: 'Montserrat', code: '+1-664'},
    {Component: MT, title: 'Malta', code: '+356'},
    {Component: MU, title: 'Mauritius', code: '+230'},
    {Component: MV, title: 'Maldives', code: '+960'},
    {Component: MW, title: 'Malawi', code: '+265'},
    {Component: MX, title: 'Mexico', code: '+52'},
    {Component: MY, title: 'Malaysia', code: '+60'},
    {Component: MZ, title: 'Mozambique', code: '+258'},
    {Component: NA, title: 'Namibia', code: '+264'},
    {Component: NC, title: 'New Caledonia', code: '+687'},
    {Component: NE, title: 'Niger', code: '+227'},
    {Component: NF, title: 'Norfolk Island', code: '+672'},
    {Component: NG, title: 'Nigeria', code: '+234'},
    {Component: NI, title: 'Nicaragua', code: '+505'},
    {Component: NL, title: 'Netherlands', code: '+31'},
    {Component: NO, title: 'Norway', code: '+47'},
    {Component: NP, title: 'Nepal', code: '+977'},
    {Component: NR, title: 'Nauru', code: '+674'},
    {Component: NU, title: 'Niue', code: '+683'},
    {Component: NZ, title: 'New Zealand', code: '+64'},
    {Component: OM, title: 'Oman', code: '+968'},
    {Component: PA, title: 'Panama', code: '+507'},
    {Component: PE, title: 'Peru', code: '+51'},
    {Component: PF, title: 'French Polynesia', code: '+689'},
    {Component: PG, title: 'Papua New Guinea', code: '+675'},
    {Component: PH, title: 'Philippines', code: '+63'},
    {Component: PK, title: 'Pakistan', code: '+92'},
    {Component: PL, title: 'Poland', code: '+48'},
    {Component: PM, title: 'Saint Pierre and Miquelon', code: '+508'},
    {Component: PN, title: 'Pitcairn Islands', code: '+64'},
    {Component: PR, title: 'Puerto Rico', code: '+1-787'},
    {Component: PS, title: 'Palestine', code: '+970'},
    {Component: PT, title: 'Portugal', code: '+351'},
    {Component: PW, title: 'Palau', code: '+680'},
    {Component: PY, title: 'Paraguay', code: '+595'},
    {Component: QA, title: 'Qatar', code: '+974'},
    {Component: RE, title: 'Réunion', code: '+262'},
    {Component: RO, title: 'Romania', code: '+40'},
    {Component: RS, title: 'Serbia', code: '+381'},
    {Component: RU, title: 'Russia', code: '+7'},
    {Component: RW, title: 'Rwanda', code: '+250'},
    {Component: SA, title: 'Saudi Arabia', code: '+966'},
    {Component: SB, title: 'Solomon Islands', code: '+677'},
    {Component: SC, title: 'Seychelles', code: '+248'},
    {Component: SD, title: 'Sudan', code: '+249'},
    {Component: SE, title: 'Sweden', code: '+46'},
    {Component: SG, title: 'Singapore', code: '+65'},
    {Component: SH, title: 'Saint Helena', code: '+290'},
    {Component: SI, title: 'Slovenia', code: '+386'},
    {Component: SJ, title: 'Svalbard and Jan Mayen', code: '+47'},
    {Component: SK, title: 'Slovakia', code: '+421'},
    {Component: SL, title: 'Sierra Leone', code: '+232'},
    {Component: SM, title: 'San Marino', code: '+378'},
    {Component: SN, title: 'Senegal', code: '+221'},
    {Component: SO, title: 'Somalia', code: '+252'},
    {Component: SR, title: 'Suriname', code: '+597'},
    {Component: SS, title: 'South Sudan', code: '+211'},
    {Component: ST, title: 'São Tomé and Príncipe', code: '+239'},
    {Component: SV, title: 'El Salvador', code: '+503'},
    {Component: SX, title: 'Sint Maarten', code: '+1-721'},
    {Component: SY, title: 'Syria', code: '+963'},
    {Component: SZ, title: 'Eswatini', code: '+268'},
    {Component: TC, title: 'Turks and Caicos Islands', code: '+1-649'},
    {Component: TD, title: 'Chad', code: '+235'},
    {Component: TG, title: 'Togo', code: '+228'},
    {Component: TH, title: 'Thailand', code: '+66'},
    {Component: TJ, title: 'Tajikistan', code: '+992'},
    {Component: TK, title: 'Tokelau', code: '+690'},
    {Component: TL, title: 'Timor-Leste', code: '+670'},
    {Component: TM, title: 'Turkmenistan', code: '+993'},
    {Component: TN, title: 'Tunisia', code: '+216'},
    {Component: TO, title: 'Tonga', code: '+676'},
    {Component: TR, title: 'Turkey', code: '+90'},
    {Component: TT, title: 'Trinidad and Tobago', code: '+1-868'},
    {Component: TV, title: 'Tuvalu', code: '+688'},
    {Component: TW, title: 'Taiwan', code: '+886'},
    {Component: TZ, title: 'Tanzania', code: '+255'},
    {Component: UA, title: 'Ukraine', code: '+380'},
    {Component: UG, title: 'Uganda', code: '+256'},
    {Component: US, title: 'United States', code: '+1'},
    {Component: UY, title: 'Uruguay', code: '+598'},
    {Component: UZ, title: 'Uzbekistan', code: '+998'},
    {Component: VA, title: 'Vatican City', code: '+39'},
    {Component: VC, title: 'Saint Vincent and the Grenadines', code: '+1-784'},
    {Component: VE, title: 'Venezuela', code: '+58'},
    {Component: VG, title: 'British Virgin Islands', code: '+1-284'},
    {Component: VI, title: 'United States Virgin Islands', code: '+1-340'},
    {Component: VN, title: 'Vietnam', code: '+84'},
    {Component: VU, title: 'Vanuatu', code: '+678'},
    {Component: WF, title: 'Wallis and Futuna', code: '+681'},
    {Component: WS, title: 'Samoa', code: '+685'},
    {Component: YE, title: 'Yemen', code: '+967'},
    {Component: YT, title: 'Mayotte', code: '+262'},
    {Component: ZA, title: 'South Africa', code: '+27'},
    {Component: ZM, title: 'Zambia', code: '+260'},
    {Component: ZW, title: 'Zimbabwe', code: '+263'}
];

export default flag;
